name: MedBay
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  gap: ^2.0.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  chat_gpt_sdk: ^2.0.6
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  image_cropper: ^3.0.2
  process_run: ^0.12.5+2
  firebase_auth: ^4.2.2
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  dropdown_formfield: ^0.1.4
  flutter_animate: ^4.1.1+1
  google_vision: ^1.0.7+6
  image_picker: ^0.8.7+1
  flutter_spinkit: ^5.1.0
  excel: ^2.0.4
  flutter_isolate: ^2.0.4
  firebase_storage: ^11.1.0
  uuid: ^3.0.7
  flutter_downloader: ^1.10.2
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.11
  geolocator: ^9.0.1
  flutter_google_places: ^0.3.0
  google_maps_flutter_web: ^0.3.2+2
  flutter_polyline_points: ^0.2.6
  google_maps_flutter: ^2.1.0
  google_maps_webservice: ^0.0.20-nullsafety.1
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
     - assests/images/
     - assests/
     - assests/auth.json
  fonts:
    - family: Raleway
      fonts:
        - asset: assests/Raleway-Regular.ttf